version: '3'
services:
  mysql:
    image: mysql:latest
    env_file: .env
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
  app:
    build: .
    env_file: .env
    command: dev
    volumes:
      - .:/app
    depends_on:
      - mysql
    ports:
      - 8000:8000
  celery:
    image: notify_app
    env_file: .env
    command: celery
    volumes:
      - .:/app
    depends_on:
      - app
  redis:
    image: redis:latest
    env_file: .env
    command: "redis-server --appendonly yes --requirepass met31415"
