# Generated by Django 2.2.6 on 2019-10-26 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('place', models.CharField(max_length=155, verbose_name='Place')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateTimeField(verbose_name='Date')),
                ('completed', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('recipients', models.ManyToManyField(blank=True, related_name='recipients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
